spring:
  redis:
    database: 0      # Redis数据库索引（默认为0）
    host: localhost   # Redis服务器地址
    port: 8888       # Redis服务器连接端口
    password:         # Redis服务器连接密码（默认为空）
    timeout: 100000  # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 300  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100    # 连接池中的最大空闲连接
        max-wait: 1000   # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 5    # 连接池中的最小空闲连接
